services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: prompthub-db
    environment:
      - 'POSTGRES_DB=prompthub'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data # 컨테이너가 꺼져도 데이터가 날아가지 않도록 볼륨 마운트

volumes:
  postgres-data: